  routers:
    Router1: ansible_host= 192.168.2.1
    Router2: ansible_host= 192.168.4.1
    Router3: ansible_host= 192.168.77.2
    Router4: ansible_host= 192.168.77.1

routers:vars 
ansible_network_os=ios
ansible_user=
ansible_password=
ansible_connection=network_cli