#BGP Configuration

- hosts: Router3
  gather_facts: false
  tasks:
    - name: BGP Config
      ios_bgp:
        config:
          bgp_as: 65000
          router_id: 192.0.0.2
          log_neighbor_changes: true
          neighbors:
            - neighbor: 192.168.77.1
              remote_as: 65100
          networks:
            - prefix: 192.168.77.0 
              masklen: 24
        operation: merge

- hosts: Router4
  gather_facts: false
  tasks:
    - name: BGP Config
      ios_bgp:
        config:
          bgp_as: 65100
          router_id: 192.0.0.3
          log_neighbor_changes: true
          neighbors:
            - neighbor: 192.168.77.2
              remote_as: 65100
          networks:
            - prefix: 192.168.77.0 
              masklen: 24
          address_family:
            - afi: ipv6
          networks:
            - prefix: 2001:DB8:FEED:77::1/64
              masklen: 64
        operation: merge


