#BGP Configuration

- hosts: Router3
  gather_facts: false
  tasks:
    - name: BGP Config Router
      ios_bgp:
        config:
          bgp_as: 65000
          router_id: 10.10.10.2
          log_neighbor_changes: true
          neighbors:
            - neighbor: 192.168.77.1
              remote_as: 65100
          networks:
            - prefix: 192.168.77.0
              masklen: 24
          address_family:
            - afi: ipv4
              safi: unicast
              redistribute:
                - protocol: ospf
                  id: 1
        operation: merge

- hosts: Router4
  gather_facts: false
  tasks:
    - name: BGP Config Router4
      ios_bgp:
        config:
          bgp_as: 65100
          router_id: 10.10.10.1
          log_neighbor_changes: true
          neighbors:
            - neighbor: 192.168.77.2
              remote_as: 65000
        operation: replace


