- host: Router3
  tasks:
    - name: BGP Config
      cisco.ios.ios_bgp:
        config:
          bgp_as: 65000
          router_id: 192.0.0.2
          log_neighbor_changes: true
          neighbors:
            - neighbor: 192.168.77.1
              remote_as: 65100

- host: Router4
  tasks:
    - name: BGP Config
      cisco.ios.ios_bgp:
        config:
          bgp_as: 65100
          router_id: 192.0.0.3
          log_neighbor_changes: true
          neighbors:
            - neighbor: 192.168.77.2
              remote_as: 65000

