#BGP Configuration

- hosts: Router3
  gather_facts: false
  tasks:
    - name: BGP Config Router
      ios_bgp:
        config:
          bgp_as: 65000
          router_id: 10.10.10.2
          log_neighbor_changes: true
          neighbors:
            - neighbor: 192.168.77.1
              remote_as: 65100
          networks:
            - prefix: 192.168.77.0
              masklen: 24
        operation: merge

    - name: BGP Config IPv6 Router3
      cisco.ios.ios_bgp_address_family:
        config:
          as_number: 65000
          address_family:
            - afi: ipv6
              safi: unicast
              neighbor:
               - address: 2001:db8:feed:77::1
                 remote_as: 65100


- hosts: Router4
  gather_facts: false
  tasks:
    - name: BGP Config Router4
      ios_bgp:
        config:
          bgp_as: 65100
          router_id: 10.10.10.1
          log_neighbor_changes: true
          neighbors:
            - neighbor: 192.168.77.2
              remote_as: 65000
        operation: replace

    - name: BGP Config IPv6 Router4
      cisco.ios.ios_bgp_address_family:
        config:
          as_number: 65100
          address_family:
            - afi: ipv6
              safi: unicast
              neighbor:
               - address: 2001:db8:feed:77::2
                 remote_as: 65000
              network:
              - address: 2001:db8:cafe:4::/64
              redistribute: ospf 



