- host: Router 1
  tasks:
   - name: EIGRP Config
        ios_config:
          lines:
          - eigrp router-id 192.168.1.1
          - network 192.168.2.0 0.0.0.255
          - passive-interface loopback0
          parents: router eigrp 65000

- host: Router 2
  tasks:
   - name: EIGRP Config
        ios_config:
          lines:
          - eigrp router-id 192.168.1.2
          - network 192.168.2.0 0.0.0.255
          - passive-interface loopback0
          parents: router eigrp 65000