#EIGRP Configuration

- hosts: Router1
  gather_facts: false
  tasks:
  - name: EIGRP Config
    cisco.ios.ios_config:
      lines:
        - eigrp router-id 192.168.1.1
        - network 192.168.2.0 0.0.0.255
        - passive-interface loopback0
        - ipv6 router eigrp 65001
        - router-id 1.1.1.2
      parents: router eigrp 65000
  - name: Eigrp Ipv6 config
    cisco.ios.ios_config:
      lines:
        - ipv6 eigrp 65001
      parents: Interface GigabitEthernet0/1

- hosts: Router2
  tasks:
  - name: EIGRP Config
    cisco.ios.ios_config:
      lines:
        - eigrp router-id 192.168.1.2
        - passive-interface loopback0
        - redistribute ospf 1
        - network 192.168.2.0 0.0.0.255
        - network 192.168.4.0 0.0.0.255
        - network 192.168.77.0 0.0.0.255
        - ipv6 router eigrp 65001
        - router-id 1.1.1.1
        - redistribute ospf 2
      parents: router eigrp 65000
  - name: Eigrp Ipv6 config
    cisco.ios.ios_config:
      lines:
        - ipv6 eigrp 65001
      parents: Interface GigabitEthernet0/0