#Implemnting GRE Tunnel
- hosts: Router3
  gather_facts: false
  tasks:
  - name: ACL2
    cisco.ios.ios_config
      lines:
        - permit ip any any
      parents: ip access-list extended VPN-ACL3

  - name: Config of GRE from Router3 into Router1
    cisco.ios.ios_config:
      lines:
        - encryption aes 256
        - authentication pre-share
        - group 1
        - lifetime 82000
        - crypto isakmp key cisco1 address 192.168.77.1
      parents:  crypto isakmp policy 10

  - name: Config of GRE from Router3 into Router1
    cisco.ios.ios_config:
      lines:
        - crypto map MAP1 100 ipsec-isakmp
        - match address VPN-ACL3
        - set pfs group1
        - set transform-set VPN12
        - set security-association lifetime seconds 86000
        - set peer 192.168.77.1
      parents: crypto ipsec transform-set VPN12 esp-aes 256 esp-sha-hmac

  - name: Config of GRE from Router3 into Router1
    cisco.ios.ios_config:
      lines:
        - crypto map MAP1
      parents: interface GigabitEthernet0/1

  - name: Config of GRE from Router3 into Router1
    cisco.ios.ios_config:
      lines:
        - Ip address 172.20.10.1 255.255.255.252
        - tunnel source GigabitEthernet0/1
        - tunnel destination 192.168.77.1
        - tunnel mode gre ip
      parents: interface Tunnel3

- hosts: Router4
  gather_facts: false
  tasks:
  - name: ACL
    cisco.ios.ios_config
      lines:
        - permit ip any any
      parents: ip access-list extended VPN-ACL3

  - name: Config of GRE from Router4 into Router1
    cisco.ios.ios_config:
      lines:
        - encryption aes 256
        - authentication pre-share
        - group 1
        - lifetime 82000
        - crypto isakmp key cisco1 address 192.168.77.2
      parents:  crypto isakmp policy 10
  - name: Config of GRE from Router4 into Router1

    cisco.ios.ios_config:
      lines:
        - crypto map MAP1 100 ipsec-isakmp
        - set pfs group1
        - set transform-set VPN12
        - set security-association lifetime seconds 86000
        - set peer 192.168.77.2
      parents: crypto ipsec transform-set VPN12 esp-aes 256 esp-sha-hmac

  - name: Config of GRE from Router4 into Router1
    cisco.ios.ios_config:
      lines:
        - crypto map MAP1
      parents: interface GigabitEthernet0/0

  - name: Config of GRE from Router4 into Router1
    cisco.ios.ios_config:
      lines: 
        - Ip address 172.20.10.2 255.255.255.252
        - tunnel source GigabitEthernet0/0
        - tunnel destination 192.168.77.2
        - tunnel mode gre ip
      parents: interface Tunnel3