- hosts: Router1
  gather_facts: false
  tasks:
  - name: Loopback0
    cisco.ios.ios_config:
      lines:
        - description Loopback
        - ip address 192.168.1.0 255.255.255.255
        - ipv6 address 2001:DB8:CAFE:1::/64 eui-64
      parents: interface Loopback0
  - name: Int Loopback1
    cisco.ios.ios_config:
      lines:
        - description LoopbackEigrp
        - ip address 192.168.6.0 255.255.255.255
        - ipv6 address 2001:DB8:CAFE:6::/64 eui-64
      parents: interface Loopback1

- hosts: Router2
  gather_facts: false
  tasks:
  - name: Loopback0
#Loopback Interface configuration 
    cisco.ios.ios_config:
      lines:
        - description Loopback
        - ip address 192.168.3.0 255.255.255.255
        - ipv6 address 2001:DB8:CAFE:1::/64 eui-64
      parents: interface Loopback0
 

- hosts: Router3
  gather_facts: false
  tasks:
  - name: Loopback0
    cisco.ios.ios_config:
      lines:
        - description Loopback
        - ip address 192.168.5.0 255.255.255.255
        - ipv6 address 2001:DB8:CAFE:5::/64 eui-64
      parents: interface Loopback0

- hosts: Router4
  gather_facts: false
  tasks:
  - name: Loopback0
    cisco.ios.ios_config:
      lines:
        - description Loopback
        - ip address 192.168.99.0 255.255.255.255
        - ipv6 address 2001:DB8:99:1::/64 eui-64
      parents: interface Loopback0
  
