#OSPF Configuration 
#afi= address family indicator

- hosts: Router2
  gather_facts: false
  tasks:
  - name: Merge provided OSPFV3 configuration
    cisco.ios.ios_ospf:
      config:
        processes:
          - process_id: 1
            max_metric:
              router_lsa: true
              on_startup:
                time: 110
            address_family:
              - afi: ipv4
                unicast: true
                adjacency:
                  max_adjacency: 50
                areas:
                  - area_id: 1
                    nssa:
                      default_information_originate:
                        metric: 25
                        nssa_only: true
        state: Merge
