#OSPF Configuration 
#afi= address family indicator

- hosts: Router2
  gather_facts: false
  tasks:
    - name: Router2 test
      cisco.ios.ios_ospfv2:
        config:
         processes:
           - process_id: 1
             areas:
               - area_id: "0"
                 capability: false
                 authentication:
                   enable: false
             network:
               - address: 192.168.4.0
                 wildcard: 0.0.0.255
                area: 0
 
        state: replaced
