#OSPF Configuration 
#afi= address family indicator

- hosts: Router2
  gather_facts: false
  tasks:
    - name: Merge provided OSPFV3 configuration
      cisco.ios.ios_ospfv3:
        config:
          processes:
            - process_id: 1
              address_family:
               - afi: ipv4
                 unicast: true
                 adjacency:
                  max_adjacency: 50
                 areas:
                   - area_id: 1
                     nssa:
                       default_information_originate:
                         metric: 25
                         nssa_only: true
        state: merged
