#OSPF Configuration 
#afi= address family indicator

- hosts: Router2
  gather_facts: false
  tasks:
    - name: Router2
      cisco.ios.ios_ospfv2:
          config:
            address_family:
              - afi: ipv4
                process:
                  id: 10
                  area_id: 0
            network:
            - address: 192.168.4.0
              wildcard: 0.0.0.255
              area: 0

