#OSPF Configuration 
#afi= address family indicator

- hosts: Router2
  gather_facts: false
  tasks:
    - name: Router2 test
      cisco.ios.ios_ospf_interfaces:
        config:
          - name: GigabitEthernet0/2
            address_family:
              - afi: ipv4
                process:
                  id: 1
                  area_id: 0
                network:
                  broadcast: true

        state: replaced

- hosts: Router3
  gather_facts: false
  tasks:
    - name: Router3 test
      cisco.ios.ios_ospf_interfaces:
        config:
          - name: GigabitEthernet0/0
            address_family:
              - afi: ipv4
                process:
                  id: 1
                  area_id: 0
                network:
                  broadcast: true

        state: replaced


- hosts: Router3
  gather_facts: false
  tasks:
    - name: Merge the provided configuration with the existing running configuration
      cisco.nxos.nxos_ospfv3:
        config:
          processes:
           - process_id: 100
             router_id: 203.0.113.20
             address_family:
               afi: ipv6
               safi: unicast
               areas:
                 - area_id: 0.0.0.100
                   ranges:
                   - prefix: 2001:db2::/32
          state: merged