#OSPF Configuration 
#afi= address family indicator

- hosts: Router2
  gather_facts: false
  tasks:
  - name: Merge provided OSPFV3 configuration
    ios_ospfv3:
      config:
        processes:
          - process_id: 1
            max_metric:
              router_lsa: true
              on_startup:
                time: 110
            address_family:
              - afi: ipv4
                unicast: true
                vrf: blue
                adjacency:
                  min_adjacency: 50
                  max_adjacency: 50
                areas:
                  - area_id: 25
                    nssa:
                      default_information_originate:
                        metric: 25
                        nssa_only: true
            areas:
             - area_id: "10"
               nssa:
                  default_information_originate:
                    metric: 10
                    nssa_only: true
        state: Merge
