#OSPF Configuration 
#afi= address family indicator

- hosts: Router2
  gather_facts: false
  tasks:
    - name: Merge provided OSPFV3 configuration
      cisco.ios.ios_ospfv3:
        config:
          processes:

        state: merged
