#OSPF Configuration 
#afi= address family indicator

- hosts: Router2
  gather_facts: false
  tasks:
    - name: Router2 OSPF
      cisco.ios.ios_ospf_interfaces:
        config:
          - name: GigabitEthernet0/2
            address_family:
              - afi: ipv4
                process:
                  id: 1
                  area_id: 0
                network:
                  broadcast: true
            address_family:
              - afi: ipv6
                process:
                  id: 2
                  area_id: 0
                network:
                  broadcast: true
        state: merged

- hosts: Router3
  gather_facts: false
  tasks:
    - name: Router3 OSPF
      cisco.ios.ios_ospf_interfaces:
        config:
          - name: GigabitEthernet0/0
            address_family:
              - afi: ipv4 
                process:
                  id: 1
                  area_id: 0
                network:
                  broadcast: true
            address_family:
              - afi: ipv6
                process:
                  id: 2
                  area_id: 0
                network:
                  broadcast: true
        state: merged

