#redistributes and broadcastes network ipv4 and ipv6 between all routing protocols
- hosts: Router2
  gather_facts: false
  tasks:
  - name: Routes from EIGRP Into OSPF
    cisco.ios.ios_config:
      lines:
        - redistribute eigrp 65000 subnets
      parents: router ospf 1

  - name: Routes from OSPF Into EIGRP
    cisco.ios.ios_config:
      lines:
        - redistribute ospf 1
        - redistribute connected
      parents: router eigrp 65000

  - name: IPv6 Router 3 redistribute BGP Into OSPF
    cisco.ios.ios_config:
      lines:
        - redistribute connected
      parents:
      - router ospfv3 2
      - address-family ipv6

- hosts: Router3
  gather_facts: false
  tasks:
  - name: Routes from BGP into OSPF
    cisco.ios.ios_config:
      lines:
        - redistribute bgp 65000 subnets
        - redistribute connected
      parents: Router OSPF 1

  - name: Routes from OSPF into BGP
    cisco.ios.ios_config:
      lines:
        - redistribute ospf 1
      parents: router bgp 65000 

  - name: IPv6 Router 3 redistribute OSPF Into BGP
    cisco.ios.ios_config:
      lines:
        - redistribute ospfv3 2
      parents: 
      - router bgp 65000
      - address-family ipv6

  - name: IPv6 Router 3 redistribute BGP Into OSPF
    cisco.ios.ios_config:
      lines:
        - redistribute bgp 65000
        - redistribute connected
      parents:
      - router ospfv3 2
      - address-family ipv6