#redistributes and broadcastes network 192.168.4.0 in ipv4 1
- hosts: Router2
  gather_facts: false
  tasks:
  - name: Routes from EIGRP Into OSPF
    cisco.ios.ios_config:
      lines:
        - redistribute eigrp 65000 subnets
      parents: router ospf 1
  - name: Routes from OSPF Into EOGRP
    cisco.ios.ios_config:
      lines:
        - redistribute ospf 1
      parents: router eigrp 65000
  - name: Routes from ipv6 eigrp into ipv6 ospf
    cisco.ios.ios_config:
      lines:
        - redistribute eigrp 65001 subnets
        - router eigrp 65001
        - redistribute ospf 2
      parents: router ospf 2

- hosts: Router3
  gather_facts: false
  tasks:
  - name: Routes from BGP into OSPF
    cisco.ios.ios_config:
      lines:
        - redistribute bgp 65000 subnets
        - redistribute connected
      parents: Router OSPF 1
  - name: Routes from OSPF into BGP
    cisco.ios.ios_config:
      lines:
        - redistribute ospf 1
      parents: router bgp 65000 
