
- hosts: Router1
  gather_facts: false
  tasks:
    - name: Router SNMP configuration
      cisco.ios.ios_snmp_server:
        config:

          groups:
            - group: mergedGroup
              version: v3
              version_option: auth
        state: replaced

