
- hosts: Router1
  gather_facts: false

    - name: Router SNMP configuration
      cisco.ios.ios_snmp_server:
        config:
          communities:
              name: ahmedASA
              rw: true
        state: replaced
